# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts and Essays
email: json.barnes@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jazzyb.github.io" # the base hostname & protocol for your site
github_username:  jazzyb

# Build settings
markdown: kramdown
